// NOTE: generated by app, keep file as UTF-8 without BOM
package com.example.curs_alexander.ui.home.quickactions

import androidx.annotation.ColorRes
import androidx.annotation.DrawableRes
import androidx.core.os.bundleOf
import com.example.curs_alexander.R
import com.example.curs_alexander.ui.measurements.HealthMeasurementAddFragment
import com.example.curs_alexander.ui.reminders.RemindersFragment

/** Доступные типы быстрых действий на главном экране. */
enum class QuickActionType(
    val id: String,
    val titleRes: Int,
    val navDestinationId: Int,
    val navArgs: android.os.Bundle? = null,
    @DrawableRes val iconRes: Int,
    @ColorRes val accentColorRes: Int
) {
    // --- Добавление данных (1 действие вместо захода в разделы) ---
    ADD_PRESSURE(
        id = "add_pressure",
        titleRes = R.string.home_action_add_pressure,
        navDestinationId = R.id.healthMeasurementAddFragment,
        navArgs = bundleOf(HealthMeasurementAddFragment.ARG_INITIAL_TYPE to HealthMeasurementAddFragment.INITIAL_TYPE_BP),
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_measurements
    ),
    ADD_PULSE(
        id = "add_pulse",
        titleRes = R.string.home_action_add_pulse,
        navDestinationId = R.id.healthMeasurementAddFragment,
        navArgs = bundleOf(HealthMeasurementAddFragment.ARG_INITIAL_TYPE to HealthMeasurementAddFragment.INITIAL_TYPE_PULSE),
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_measurements
    ),
    ADD_SYMPTOM(
        id = "add_symptom",
        titleRes = R.string.home_action_add_symptom,
        navDestinationId = R.id.symptomAddFragment,
        iconRes = R.drawable.ic_symptom_24,
        accentColorRes = R.color.qa_symptoms
    ),
    ADD_REMINDER(
        id = "add_reminder",
        titleRes = R.string.home_action_add_reminder,
        navDestinationId = R.id.remindersFragment,
        navArgs = bundleOf(RemindersFragment.ARG_OPEN_ADD_DIALOG to true),
        iconRes = R.drawable.ic_reminder_24,
        accentColorRes = R.color.qa_reminders
    ),

    // --- Быстрые переходы (2+ клика экономии) ---
    OPEN_ANALYTICS(
        id = "open_analytics",
        titleRes = R.string.home_action_open_analytics,
        navDestinationId = R.id.analyticsFragment,
        iconRes = R.drawable.ic_analytics_24,
        accentColorRes = R.color.qa_analytics
    ),
    OPEN_DATA_STATUS(
        id = "open_data_status",
        titleRes = R.string.home_action_open_data_status,
        navDestinationId = R.id.dataStatusFragment,
        iconRes = R.drawable.ic_info_24,
        accentColorRes = R.color.qa_analytics
    ),
    OPEN_MEDICAL_CARD(
        id = "open_medical_card",
        titleRes = R.string.home_action_open_medical_card,
        navDestinationId = R.id.medicalCardFragment,
        iconRes = R.drawable.ic_medical_card_24,
        accentColorRes = R.color.qa_medical_card
    ),
    OPEN_USER_PARAMS(
        id = "open_user_params",
        titleRes = R.string.home_action_open_user_params,
        navDestinationId = R.id.userParamsFragment,
        iconRes = R.drawable.ic_analytics_24,
        accentColorRes = R.color.qa_analytics
    ),
    OPEN_SETTINGS(
        id = "open_settings",
        titleRes = R.string.home_action_open_settings,
        navDestinationId = R.id.settingsFragment,
        iconRes = R.drawable.ic_settings_24,
        accentColorRes = R.color.qa_settings
    ),
    OPEN_EDUCATION(
        id = "open_education",
        titleRes = R.string.home_action_open_education,
        navDestinationId = R.id.educationListFragment,
        iconRes = R.drawable.ic_info_24,
        accentColorRes = R.color.qa_settings
    );

    companion object {
        fun fromId(id: String): QuickActionType? = entries.firstOrNull { it.id == id }
    }
}
