// NOTE: generated by app, keep file as UTF-8 without BOM
package com.example.curs_alexander.ui.home.quickactions

import androidx.annotation.ColorRes
import androidx.annotation.DrawableRes
import com.example.curs_alexander.R

/** Доступные типы быстрых действий на главном экране. */
enum class QuickActionType(
    val id: String,
    val titleRes: Int,
    val navDestinationId: Int,
    @DrawableRes val iconRes: Int,
    @ColorRes val accentColorRes: Int
) {
    ADD_MEASUREMENT(
        id = "add_measurement",
        titleRes = R.string.home_action_add_measurement,
        navDestinationId = R.id.healthMeasurementAddFragment,
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_measurements
    ),
    ADD_SYMPTOM(
        id = "add_symptom",
        titleRes = R.string.home_action_add_symptom,
        navDestinationId = R.id.symptomAddFragment,
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_symptoms
    ),
    ADD_REMINDER(
        id = "add_reminder",
        titleRes = R.string.home_action_add_reminder,
        navDestinationId = R.id.remindersFragment,
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_reminders
    ),

    OPEN_MEASUREMENTS(
        id = "open_measurements",
        titleRes = R.string.home_section_measurements,
        navDestinationId = R.id.healthMeasurementsFragment,
        iconRes = R.drawable.ic_measurements_24,
        accentColorRes = R.color.qa_measurements
    ),
    OPEN_SYMPTOMS(
        id = "open_symptoms",
        titleRes = R.string.home_section_symptoms,
        navDestinationId = R.id.symptomsListFragment,
        iconRes = R.drawable.ic_symptom_24,
        accentColorRes = R.color.qa_symptoms
    ),
    OPEN_REMINDERS(
        id = "open_reminders",
        titleRes = R.string.home_section_reminders,
        navDestinationId = R.id.remindersFragment,
        iconRes = R.drawable.ic_reminder_24,
        accentColorRes = R.color.qa_reminders
    ),
    OPEN_ANALYTICS(
        id = "open_analytics",
        titleRes = R.string.analytics_title,
        navDestinationId = R.id.analyticsFragment,
        iconRes = R.drawable.ic_analytics_24,
        accentColorRes = R.color.qa_analytics
    ),
    OPEN_MEDICAL_CARD(
        id = "open_medical_card",
        titleRes = R.string.medical_card_title,
        navDestinationId = R.id.medicalCardFragment,
        iconRes = R.drawable.ic_medical_card_24,
        accentColorRes = R.color.qa_medical_card
    ),
    OPEN_SETTINGS(
        id = "open_settings",
        titleRes = R.string.settings_title,
        navDestinationId = R.id.settingsFragment,
        iconRes = R.drawable.ic_settings_24,
        accentColorRes = R.color.qa_settings
    );

    companion object {
        fun fromId(id: String): QuickActionType? = values().firstOrNull { it.id == id }
    }
}
