// NOTE: generated by app, keep file as UTF-8 without BOM
package com.example.curs_alexander.ui.home.quickactions

import androidx.annotation.ColorRes
import androidx.annotation.DrawableRes
import androidx.core.os.bundleOf
import com.example.curs_alexander.R
import com.example.curs_alexander.ui.measurements.HealthMeasurementAddFragment
import com.example.curs_alexander.ui.reminders.RemindersFragment

/** Доступные типы быстрых действий на главном экране. */
enum class QuickActionType(
    val id: String,
    val titleRes: Int,
    val navDestinationId: Int,
    val navArgs: android.os.Bundle? = null,
    @DrawableRes val iconRes: Int,
    @ColorRes val accentColorRes: Int
) {
    ADD_PRESSURE(
        id = "add_pressure",
        titleRes = R.string.home_action_add_pressure,
        navDestinationId = R.id.healthMeasurementAddFragment,
        navArgs = bundleOf(HealthMeasurementAddFragment.ARG_INITIAL_TYPE to HealthMeasurementAddFragment.INITIAL_TYPE_BP),
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_measurements
    ),
    ADD_PULSE(
        id = "add_pulse",
        titleRes = R.string.home_action_add_pulse,
        navDestinationId = R.id.healthMeasurementAddFragment,
        navArgs = bundleOf(HealthMeasurementAddFragment.ARG_INITIAL_TYPE to HealthMeasurementAddFragment.INITIAL_TYPE_PULSE),
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_measurements
    ),
    ADD_SYMPTOM(
        id = "add_symptom",
        titleRes = R.string.home_action_add_symptom,
        navDestinationId = R.id.symptomAddFragment,
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_symptoms
    ),
    ADD_REMINDER(
        id = "add_reminder",
        titleRes = R.string.home_action_add_reminder,
        navDestinationId = R.id.remindersFragment,
        navArgs = bundleOf(RemindersFragment.ARG_OPEN_ADD_DIALOG to true),
        iconRes = R.drawable.ic_add_24,
        accentColorRes = R.color.qa_reminders
    );

    companion object {
        fun fromId(id: String): QuickActionType? = entries.firstOrNull { it.id == id }
    }
}
